name: ColtSebastianTaylor
favicon: null
layout_spectrum: 0.46240388764999807
typography_spectrum: 0.9667334072291851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2641154108569026
  lightness: 0.6937015925068408
  saturation: 0.905979081755504
  rhythmicContrast: 0.12176549318246543
purpose: []
