name: ColtSebastianTaylor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76092
title: Colt Sebastian Taylor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-29235913-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ffffff'
    - '#c0181d'
    - '#717171'
    - '#e3874c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
