name: ColtSebastianTaylor
favicon: null
layout_spectrum: 0.73051
typography_spectrum: 0.75738
title: Colt Sebastian Taylor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-29235913-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e8cb'
    - '#2c4947'
    - '#709f8f'
    - '#456e66'
    - '#a8825e'
  brandStrength: 0.5
  lightness: 0.6937015925068408
  saturation: 0.905979081755504
  rhythmicContrast: 0.12176549318246543
purpose: []
